import './globals.css'
import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'

const mFont = DM_Sans({
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Wahyu Koco - Profile',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={mFont.className}>{children}</body>
    </html>
  )
}
